name: Deploy React Vite portfolio ke VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Copy files to VPS using rsync (exclude .git and node_modules)
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" \
            --exclude='.git' \
            --exclude='node_modules' \
            ./ $VPS_USERNAME@$VPS_HOST:$VPS_TARGET_PATH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}
          VPS_TARGET_PATH: ${{ secrets.VPS_TARGET_PATH }}
